import { db } from '@/firebaseAdmin';
import { NewsletterFormType } from '../types/NewsletterFormType';

export async function createNewsletterSubscription(
  data: NewsletterFormType,
): Promise<boolean> {
  // TODO fully generated by AI, check first...

  // Create a new newsletter subscription
  const subscriptionRef = db.collection('newsletter_subscriptions').doc();
  const subscriptionId = subscriptionRef.id;
  const newSubscription = {
    ...data,
    id: subscriptionId,
    confirmed: false,
    unsubscribed: false,
  };
  await subscriptionRef.set(newSubscription);
  return true;
}
